import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { notoSansJP } from '@/app/_ui/fonts/fonts';

export const metadata: Metadata = {
  title: 'Toolbox',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="ja">
    <body className={notoSansJP.className}>{children}</body>
    </html>
  );
}
