import type {Metadata} from "next";
import {Noto_Sans_JP} from "next/font/google";
import "./globalreset.css";
import "./globals.css";
import "./globalicon.css";
import React from "react";

const notoSansJP = Noto_Sans_JP({subsets: ["latin"], weight: ['400', '700']});
export const metadata: Metadata = {
	title: "Toolbox",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="ja">
		<body className={notoSansJP.className}>{children}</body>
		</html>
	);
}
